import { db, codurICaenTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const coduri = [
  // A - Agricultură, silvicultură și pescuit
  { cod: "0111", denumire: "Cultivarea cerealelor, cu excepția orezului, a plantelor leguminoase și a plantelor producătoare de semințe oleaginoase", sectiune: "A", diviziune: "01" },
  { cod: "0112", denumire: "Cultivarea orezului", sectiune: "A", diviziune: "01" },
  { cod: "0113", denumire: "Cultivarea legumelor și a pepenilor, a rădăcinoaselor și tuberculilor", sectiune: "A", diviziune: "01" },
  { cod: "0121", denumire: "Cultivarea strugurilor", sectiune: "A", diviziune: "01" },
  { cod: "0141", denumire: "Creșterea bovinelor de lapte", sectiune: "A", diviziune: "01" },
  { cod: "0150", denumire: "Activități în ferme mixte (cultura vegetală combinată cu creșterea animalelor)", sectiune: "A", diviziune: "01" },
  { cod: "0210", denumire: "Silvicultură și alte activități forestiere", sectiune: "A", diviziune: "02" },
  { cod: "0311", denumire: "Pescuitul maritim", sectiune: "A", diviziune: "03" },
  { cod: "0321", denumire: "Acvacultura maritimă", sectiune: "A", diviziune: "03" },
  // B - Industria extractivă
  { cod: "0610", denumire: "Extracția petrolului brut", sectiune: "B", diviziune: "06" },
  { cod: "0620", denumire: "Extracția gazelor naturale", sectiune: "B", diviziune: "06" },
  { cod: "0892", denumire: "Extracția turbei", sectiune: "B", diviziune: "08" },
  // C - Industria prelucrătoare
  { cod: "1011", denumire: "Prelucrarea și conservarea cărnii", sectiune: "C", diviziune: "10" },
  { cod: "1012", denumire: "Prelucrarea și conservarea cărnii de pasăre", sectiune: "C", diviziune: "10" },
  { cod: "1013", denumire: "Fabricarea produselor din carne (inclusiv din carne de pasăre)", sectiune: "C", diviziune: "10" },
  { cod: "1020", denumire: "Prelucrarea și conservarea peștelui, crustaceelor și moluștelor", sectiune: "C", diviziune: "10" },
  { cod: "1031", denumire: "Prelucrarea și conservarea cartofilor", sectiune: "C", diviziune: "10" },
  { cod: "1051", denumire: "Fabricarea produselor lactate și a brânzeturilor", sectiune: "C", diviziune: "10" },
  { cod: "1061", denumire: "Fabricarea produselor de morărit", sectiune: "C", diviziune: "10" },
  { cod: "1071", denumire: "Fabricarea pâinii; fabricarea prăjiturilor și a produselor proaspete de patiserie", sectiune: "C", diviziune: "10" },
  { cod: "1082", denumire: "Fabricarea produselor din cacao, a ciocolatei și a produselor zaharoase", sectiune: "C", diviziune: "10" },
  { cod: "1089", denumire: "Fabricarea altor produse alimentare n.c.a.", sectiune: "C", diviziune: "10" },
  { cod: "1101", denumire: "Fabricarea băuturilor alcoolice distilate", sectiune: "C", diviziune: "11" },
  { cod: "1105", denumire: "Fabricarea berii", sectiune: "C", diviziune: "11" },
  { cod: "1320", denumire: "Producția de țesături", sectiune: "C", diviziune: "13" },
  { cod: "1411", denumire: "Fabricarea articolelor de îmbrăcăminte din piele", sectiune: "C", diviziune: "14" },
  { cod: "1413", denumire: "Fabricarea altor articole de îmbrăcăminte exterioară", sectiune: "C", diviziune: "14" },
  { cod: "1512", denumire: "Fabricarea articolelor de voiaj și marochinărie și a articolelor de harnasamant", sectiune: "C", diviziune: "15" },
  { cod: "1610", denumire: "Tăierea și rindeluirea lemnului", sectiune: "C", diviziune: "16" },
  { cod: "1621", denumire: "Fabricarea de furnire și a panourilor de lemn", sectiune: "C", diviziune: "16" },
  { cod: "1623", denumire: "Fabricarea altor elemente de dulgherie și tâmplărie pentru construcții", sectiune: "C", diviziune: "16" },
  { cod: "1712", denumire: "Fabricarea hârtiei și cartonului", sectiune: "C", diviziune: "17" },
  { cod: "1812", denumire: "Alte activități de tipărire n.c.a.", sectiune: "C", diviziune: "18" },
  { cod: "2012", denumire: "Fabricarea coloranților și a pigmenților", sectiune: "C", diviziune: "20" },
  { cod: "2020", denumire: "Fabricarea pesticidelor și a altor produse agrochimice", sectiune: "C", diviziune: "20" },
  { cod: "2030", denumire: "Fabricarea vopselelor, lacurilor, cernelii tipografice și masticurilor", sectiune: "C", diviziune: "20" },
  { cod: "2041", denumire: "Fabricarea săpunurilor și detergenților, a produselor de întreținere și lustruire", sectiune: "C", diviziune: "20" },
  { cod: "2042", denumire: "Fabricarea parfumurilor și a produselor cosmetice (de toaletă)", sectiune: "C", diviziune: "20" },
  { cod: "2110", denumire: "Fabricarea produselor farmaceutice de bază", sectiune: "C", diviziune: "21" },
  { cod: "2120", denumire: "Fabricarea preparatelor farmaceutice", sectiune: "C", diviziune: "21" },
  { cod: "2211", denumire: "Fabricarea anvelopelor și a camerelor de aer; reșaparea și refacerea anvelopelor", sectiune: "C", diviziune: "22" },
  { cod: "2221", denumire: "Fabricarea plăcilor, foliilor, tuburilor și profilelor din material plastic", sectiune: "C", diviziune: "22" },
  { cod: "2311", denumire: "Fabricarea sticlei plate", sectiune: "C", diviziune: "23" },
  { cod: "2351", denumire: "Fabricarea cimentului", sectiune: "C", diviziune: "23" },
  { cod: "2410", denumire: "Producția de fontă, oțel și feroaliaje", sectiune: "C", diviziune: "24" },
  { cod: "2511", denumire: "Fabricarea de construcții metalice și părți componente ale structurilor metalice", sectiune: "C", diviziune: "25" },
  { cod: "2561", denumire: "Tratarea și acoperirea metalelor", sectiune: "C", diviziune: "25" },
  { cod: "2571", denumire: "Fabricarea produselor de tăiat", sectiune: "C", diviziune: "25" },
  { cod: "2611", denumire: "Fabricarea componentelor electronice", sectiune: "C", diviziune: "26" },
  { cod: "2620", denumire: "Fabricarea calculatoarelor și a echipamentelor periferice", sectiune: "C", diviziune: "26" },
  { cod: "2630", denumire: "Fabricarea echipamentelor de comunicații", sectiune: "C", diviziune: "26" },
  { cod: "2640", denumire: "Fabricarea produselor electronice de larg consum", sectiune: "C", diviziune: "26" },
  { cod: "2711", denumire: "Fabricarea motoarelor electrice, generatoarelor și transformatoarelor electrice", sectiune: "C", diviziune: "27" },
  { cod: "2751", denumire: "Fabricarea aparatelor electrocasnice", sectiune: "C", diviziune: "27" },
  { cod: "2811", denumire: "Fabricarea de motoare și turbine (cu excepția celor pentru avioane, autovehicule și motociclete)", sectiune: "C", diviziune: "28" },
  { cod: "2910", denumire: "Fabricarea autovehiculelor de transport rutier", sectiune: "C", diviziune: "29" },
  { cod: "2920", denumire: "Fabricarea caroseriilor pentru autovehicule; fabricarea de remorci și semiremorci", sectiune: "C", diviziune: "29" },
  { cod: "2930", denumire: "Fabricarea de piese și accesorii pentru autovehicule și pentru motoare de autovehicule", sectiune: "C", diviziune: "29" },
  // D - Producția și furnizarea de energie electrică și termică, gaze, apă caldă și aer condiționat
  { cod: "3511", denumire: "Producția de energie electrică", sectiune: "D", diviziune: "35" },
  { cod: "3512", denumire: "Transportul energiei electrice", sectiune: "D", diviziune: "35" },
  { cod: "3513", denumire: "Distribuția energiei electrice", sectiune: "D", diviziune: "35" },
  { cod: "3514", denumire: "Comercializarea energiei electrice", sectiune: "D", diviziune: "35" },
  { cod: "3521", denumire: "Producția de gaze", sectiune: "D", diviziune: "35" },
  { cod: "3530", denumire: "Furnizarea de abur și aer condiționat", sectiune: "D", diviziune: "35" },
  // E - Distribuția apei, salubritate, gestionarea deșeurilor, activități de decontaminare
  { cod: "3600", denumire: "Captarea, tratarea și distribuția apei", sectiune: "E", diviziune: "36" },
  { cod: "3700", denumire: "Colectarea și epurarea apelor uzate", sectiune: "E", diviziune: "37" },
  { cod: "3811", denumire: "Colectarea deșeurilor nepericuloase", sectiune: "E", diviziune: "38" },
  { cod: "3812", denumire: "Colectarea deșeurilor periculoase", sectiune: "E", diviziune: "38" },
  { cod: "3821", denumire: "Tratarea și eliminarea deșeurilor nepericuloase", sectiune: "E", diviziune: "38" },
  // F - Construcții
  { cod: "4110", denumire: "Dezvoltare (promovare) imobiliară", sectiune: "F", diviziune: "41" },
  { cod: "4120", denumire: "Lucrări de construcție a clădirilor rezidențiale și nerezidențiale", sectiune: "F", diviziune: "41" },
  { cod: "4211", denumire: "Lucrări de construcție a drumurilor și autostrăzilor", sectiune: "F", diviziune: "42" },
  { cod: "4221", denumire: "Lucrări de construcție a proiectelor utilitare pentru fluide", sectiune: "F", diviziune: "42" },
  { cod: "4311", denumire: "Lucrări de demolare a construcțiilor", sectiune: "F", diviziune: "43" },
  { cod: "4312", denumire: "Lucrări de pregătire a terenului", sectiune: "F", diviziune: "43" },
  { cod: "4321", denumire: "Lucrări de instalații electrice", sectiune: "F", diviziune: "43" },
  { cod: "4322", denumire: "Lucrări de instalații sanitare, de încălzire și de aer condiționat", sectiune: "F", diviziune: "43" },
  { cod: "4329", denumire: "Alte lucrări de instalații pentru construcții", sectiune: "F", diviziune: "43" },
  { cod: "4331", denumire: "Lucrări de ipsoserie", sectiune: "F", diviziune: "43" },
  { cod: "4332", denumire: "Lucrări de tâmplărie și dulgherie", sectiune: "F", diviziune: "43" },
  { cod: "4333", denumire: "Lucrări de pardosire și placare a pereților", sectiune: "F", diviziune: "43" },
  { cod: "4334", denumire: "Lucrări de vopsitorie, zugraveli și montare de geamuri", sectiune: "F", diviziune: "43" },
  { cod: "4391", denumire: "Lucrări de învelitori, șarpante și terase la construcții", sectiune: "F", diviziune: "43" },
  { cod: "4399", denumire: "Alte lucrări speciale de construcții n.c.a.", sectiune: "F", diviziune: "43" },
  // G - Comerț cu ridicata și cu amănuntul
  { cod: "4511", denumire: "Comerț cu autoturisme și autovehicule ușoare (sub 3,5 tone)", sectiune: "G", diviziune: "45" },
  { cod: "4520", denumire: "Întreținerea și repararea autovehiculelor", sectiune: "G", diviziune: "45" },
  { cod: "4531", denumire: "Comerț cu ridicata de piese și accesorii pentru autovehicule", sectiune: "G", diviziune: "45" },
  { cod: "4532", denumire: "Comerț cu amănuntul de piese și accesorii pentru autovehicule", sectiune: "G", diviziune: "45" },
  { cod: "4611", denumire: "Intermedieri în comerțul cu materii prime agricole, animale vii, materii prime textile și cu semifabricate", sectiune: "G", diviziune: "46" },
  { cod: "4619", denumire: "Intermedieri în comerțul cu produse diverse", sectiune: "G", diviziune: "46" },
  { cod: "4621", denumire: "Comerț cu ridicata al cerealelor, semințelor, furajelor și tutunului neprelucrat", sectiune: "G", diviziune: "46" },
  { cod: "4631", denumire: "Comerț cu ridicata al fructelor și legumelor", sectiune: "G", diviziune: "46" },
  { cod: "4632", denumire: "Comerț cu ridicata al cărnii și produselor din carne", sectiune: "G", diviziune: "46" },
  { cod: "4641", denumire: "Comerț cu ridicata al produselor textile", sectiune: "G", diviziune: "46" },
  { cod: "4651", denumire: "Comerț cu ridicata al calculatoarelor, echipamentelor periferice și software-ului", sectiune: "G", diviziune: "46" },
  { cod: "4669", denumire: "Comerț cu ridicata al altor mașini și echipamente n.c.a.", sectiune: "G", diviziune: "46" },
  { cod: "4671", denumire: "Comerț cu ridicata al combustibililor solizi, lichizi și gazoși și al produselor derivate", sectiune: "G", diviziune: "46" },
  { cod: "4690", denumire: "Comerț cu ridicata nespecializat", sectiune: "G", diviziune: "46" },
  { cod: "4711", denumire: "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse alimentare, băuturi și tutun", sectiune: "G", diviziune: "47" },
  { cod: "4719", denumire: "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse nealimentare", sectiune: "G", diviziune: "47" },
  { cod: "4721", denumire: "Comerț cu amănuntul al fructelor și legumelor proaspete, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4722", denumire: "Comerț cu amănuntul al cărnii și al produselor din carne, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4723", denumire: "Comerț cu amănuntul al peștelui, crustaceelor și moluștelor, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4724", denumire: "Comerț cu amănuntul al pâinii, produselor de patiserie și produselor zaharoase, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4741", denumire: "Comerț cu amănuntul al calculatoarelor, unităților periferice și software-ului în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4742", denumire: "Comerț cu amănuntul al echipamentului pentru telecomunicații în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4751", denumire: "Comerț cu amănuntul al textilelor, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4752", denumire: "Comerț cu amănuntul al articolelor de fierărie, al articolelor din sticlă și a celor pentru vopsit, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4753", denumire: "Comerț cu amănuntul al covoarelor, carpetelor, tapetelor și al altor acoperitoare de podea, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4761", denumire: "Comerț cu amănuntul al cărților, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4771", denumire: "Comerț cu amănuntul al îmbrăcămintei, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4772", denumire: "Comerț cu amănuntul al încălțămintei și articolelor din piele, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4773", denumire: "Comerț cu amănuntul al produselor farmaceutice, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4774", denumire: "Comerț cu amănuntul al articolelor medicale și ortopedice, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4776", denumire: "Comerț cu amănuntul al florilor, plantelor și semințelor; comerț cu amănuntul al animalelor de companie și al hranei pentru acestea, în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4777", denumire: "Comerț cu amănuntul al ceasurilor și bijuteriilor în magazine specializate", sectiune: "G", diviziune: "47" },
  { cod: "4781", denumire: "Comerț cu amănuntul al produselor alimentare, băuturilor și produselor din tutun efectuat prin standuri, chioșcuri și piețe", sectiune: "G", diviziune: "47" },
  { cod: "4791", denumire: "Comerț cu amănuntul prin intermediul caselor de comenzi sau prin Internet", sectiune: "G", diviziune: "47" },
  // H - Transport și depozitare
  { cod: "4910", denumire: "Transporturi interurbane de călători pe calea ferată", sectiune: "H", diviziune: "49" },
  { cod: "4920", denumire: "Transporturi de marfă pe calea ferată", sectiune: "H", diviziune: "49" },
  { cod: "4931", denumire: "Transporturi urbane, suburbane și metropolitane de călători", sectiune: "H", diviziune: "49" },
  { cod: "4932", denumire: "Transporturi cu taxiuri", sectiune: "H", diviziune: "49" },
  { cod: "4939", denumire: "Alte transporturi terestre de călători n.c.a.", sectiune: "H", diviziune: "49" },
  { cod: "4941", denumire: "Transporturi rutiere de mărfuri", sectiune: "H", diviziune: "49" },
  { cod: "4942", denumire: "Servicii de mutare", sectiune: "H", diviziune: "49" },
  { cod: "5110", denumire: "Transporturi aeriene de pasageri", sectiune: "H", diviziune: "51" },
  { cod: "5210", denumire: "Depozitări", sectiune: "H", diviziune: "52" },
  { cod: "5221", denumire: "Activități de servicii anexe pentru transporturi terestre", sectiune: "H", diviziune: "52" },
  { cod: "5320", denumire: "Alte activități poștale și de curier", sectiune: "H", diviziune: "53" },
  // I - Hoteluri și restaurante
  { cod: "5510", denumire: "Hoteluri și alte facilități de cazare similare", sectiune: "I", diviziune: "55" },
  { cod: "5520", denumire: "Facilități de cazare pentru vacanțe și perioade de scurtă durată", sectiune: "I", diviziune: "55" },
  { cod: "5530", denumire: "Parcuri pentru rulote, campinguri și tabere", sectiune: "I", diviziune: "55" },
  { cod: "5590", denumire: "Alte servicii de cazare", sectiune: "I", diviziune: "55" },
  { cod: "5610", denumire: "Restaurante", sectiune: "I", diviziune: "56" },
  { cod: "5621", denumire: "Activități de alimentație (catering) pentru evenimente", sectiune: "I", diviziune: "56" },
  { cod: "5629", denumire: "Alte activități de alimentație n.c.a.", sectiune: "I", diviziune: "56" },
  { cod: "5630", denumire: "Baruri și alte activități de servire a băuturilor", sectiune: "I", diviziune: "56" },
  // J - Informații și comunicații
  { cod: "5811", denumire: "Activități de editare a cărților", sectiune: "J", diviziune: "58" },
  { cod: "5813", denumire: "Activități de editare a ziarelor", sectiune: "J", diviziune: "58" },
  { cod: "5814", denumire: "Activități de editare a revistelor și periodicelor", sectiune: "J", diviziune: "58" },
  { cod: "5819", denumire: "Alte activități de editare", sectiune: "J", diviziune: "58" },
  { cod: "5821", denumire: "Activități de editare a jocurilor de calculator", sectiune: "J", diviziune: "58" },
  { cod: "5829", denumire: "Activități de editare a altor produse software", sectiune: "J", diviziune: "58" },
  { cod: "5911", denumire: "Activități de producție cinematografică, video și de programe de televiziune", sectiune: "J", diviziune: "59" },
  { cod: "5920", denumire: "Activități de realizare a înregistrărilor audio și activități de editare muzicală", sectiune: "J", diviziune: "59" },
  { cod: "6010", denumire: "Activități de difuzare a programelor de radio", sectiune: "J", diviziune: "60" },
  { cod: "6020", denumire: "Activități de producție și difuzare a programelor de televiziune", sectiune: "J", diviziune: "60" },
  { cod: "6110", denumire: "Activități de telecomunicații prin rețele cu cablu", sectiune: "J", diviziune: "61" },
  { cod: "6120", denumire: "Activități de telecomunicații prin rețele fără cablu (exclusiv prin satelit)", sectiune: "J", diviziune: "61" },
  { cod: "6130", denumire: "Activități de telecomunicații prin satelit", sectiune: "J", diviziune: "61" },
  { cod: "6190", denumire: "Alte activități de telecomunicații", sectiune: "J", diviziune: "61" },
  { cod: "6201", denumire: "Activități de realizare a soft-ului la comandă (software orientat client)", sectiune: "J", diviziune: "62" },
  { cod: "6202", denumire: "Activități de consultanță în tehnologia informației", sectiune: "J", diviziune: "62" },
  { cod: "6203", denumire: "Activități de management (gestiune și exploatare) a mijloacelor de calcul", sectiune: "J", diviziune: "62" },
  { cod: "6209", denumire: "Alte activități de servicii privind tehnologia informației", sectiune: "J", diviziune: "62" },
  { cod: "6311", denumire: "Prelucrarea datelor, administrarea paginilor web și activități conexe", sectiune: "J", diviziune: "63" },
  { cod: "6312", denumire: "Activități ale portalurilor web", sectiune: "J", diviziune: "63" },
  { cod: "6391", denumire: "Activități ale agențiilor de știri", sectiune: "J", diviziune: "63" },
  { cod: "6399", denumire: "Alte activități de servicii informaționale n.c.a.", sectiune: "J", diviziune: "63" },
  // K - Intermedieri financiare și asigurări
  { cod: "6411", denumire: "Activități ale băncilor centrale", sectiune: "K", diviziune: "64" },
  { cod: "6419", denumire: "Alte activități de intermedieri monetare", sectiune: "K", diviziune: "64" },
  { cod: "6420", denumire: "Activități ale holdingurilor", sectiune: "K", diviziune: "64" },
  { cod: "6430", denumire: "Fonduri mutuale și alte entități financiare similare", sectiune: "K", diviziune: "64" },
  { cod: "6491", denumire: "Activități de leasing financiar", sectiune: "K", diviziune: "64" },
  { cod: "6492", denumire: "Alte activități de creditare", sectiune: "K", diviziune: "64" },
  { cod: "6499", denumire: "Alte intermedieri financiare n.c.a.", sectiune: "K", diviziune: "64" },
  { cod: "6511", denumire: "Activități de asigurare de viață", sectiune: "K", diviziune: "65" },
  { cod: "6512", denumire: "Alte activități de asigurare (cu excepția activităților de asigurare de viață)", sectiune: "K", diviziune: "65" },
  { cod: "6622", denumire: "Activități ale agenților și brokerilor de asigurări", sectiune: "K", diviziune: "66" },
  // L - Tranzacții imobiliare
  { cod: "6810", denumire: "Cumpărarea și vânzarea de bunuri imobiliare proprii", sectiune: "L", diviziune: "68" },
  { cod: "6820", denumire: "Închirierea și subînchirierea bunurilor imobiliare proprii sau închiriate", sectiune: "L", diviziune: "68" },
  { cod: "6831", denumire: "Agenții imobiliare", sectiune: "L", diviziune: "68" },
  { cod: "6832", denumire: "Administrarea imobilelor pe bază de comision sau contract", sectiune: "L", diviziune: "68" },
  // M - Activități profesionale, științifice și tehnice
  { cod: "6910", denumire: "Activități juridice", sectiune: "M", diviziune: "69" },
  { cod: "6920", denumire: "Activități de contabilitate și audit financiar; consultanță în domeniu fiscal", sectiune: "M", diviziune: "69" },
  { cod: "7010", denumire: "Activități ale direcțiilor (centralelor), birourilor administrative centralizate", sectiune: "M", diviziune: "70" },
  { cod: "7011", denumire: "Activități de management al holdingurilor", sectiune: "M", diviziune: "70" },
  { cod: "7021", denumire: "Activități de consultanță în domeniul relațiilor publice și al comunicării", sectiune: "M", diviziune: "70" },
  { cod: "7022", denumire: "Activități de consultanță pentru afaceri și management", sectiune: "M", diviziune: "70" },
  { cod: "7111", denumire: "Activități de arhitectură", sectiune: "M", diviziune: "71" },
  { cod: "7112", denumire: "Activități de inginerie și consultanță tehnică legate de acestea", sectiune: "M", diviziune: "71" },
  { cod: "7120", denumire: "Activități de testări și analize tehnice", sectiune: "M", diviziune: "71" },
  { cod: "7211", denumire: "Cercetare-dezvoltare în biotehnologie", sectiune: "M", diviziune: "72" },
  { cod: "7219", denumire: "Cercetare-dezvoltare în alte științe naturale și inginerie", sectiune: "M", diviziune: "72" },
  { cod: "7220", denumire: "Cercetare-dezvoltare în științe sociale și umaniste", sectiune: "M", diviziune: "72" },
  { cod: "7311", denumire: "Activități ale agențiilor de publicitate", sectiune: "M", diviziune: "73" },
  { cod: "7312", denumire: "Servicii de reprezentare media", sectiune: "M", diviziune: "73" },
  { cod: "7320", denumire: "Activități de studiere a pieței și de sondare a opiniei publice", sectiune: "M", diviziune: "73" },
  { cod: "7410", denumire: "Activități de design specializat", sectiune: "M", diviziune: "74" },
  { cod: "7420", denumire: "Activități fotografice", sectiune: "M", diviziune: "74" },
  { cod: "7430", denumire: "Activități de traducere și interpretare", sectiune: "M", diviziune: "74" },
  { cod: "7490", denumire: "Alte activități profesionale, științifice și tehnice n.c.a.", sectiune: "M", diviziune: "74" },
  { cod: "7500", denumire: "Activități veterinare", sectiune: "M", diviziune: "75" },
  // N - Activități de servicii administrative și activități de servicii suport
  { cod: "7711", denumire: "Activități de închiriere și leasing cu autoturisme și autovehicule rutiere ușoare", sectiune: "N", diviziune: "77" },
  { cod: "7712", denumire: "Activități de închiriere și leasing cu camioane", sectiune: "N", diviziune: "77" },
  { cod: "7730", denumire: "Activități de închiriere și leasing cu mașini și echipamente agricole", sectiune: "N", diviziune: "77" },
  { cod: "7810", denumire: "Activități ale agențiilor de plasare a forței de muncă", sectiune: "N", diviziune: "78" },
  { cod: "7820", denumire: "Activități de contractare, pe baze temporare, a personalului", sectiune: "N", diviziune: "78" },
  { cod: "7830", denumire: "Servicii de furnizare și management a forței de muncă", sectiune: "N", diviziune: "78" },
  { cod: "7911", denumire: "Activități ale agențiilor turistice", sectiune: "N", diviziune: "79" },
  { cod: "7912", denumire: "Activități ale tur-operatorilor", sectiune: "N", diviziune: "79" },
  { cod: "7990", denumire: "Alte servicii de rezervare și asistență turistică", sectiune: "N", diviziune: "79" },
  { cod: "8010", denumire: "Activități de protecție și gardă", sectiune: "N", diviziune: "80" },
  { cod: "8020", denumire: "Activități de servicii privind sistemele de securizare", sectiune: "N", diviziune: "80" },
  { cod: "8110", denumire: "Activități de servicii suport combinate", sectiune: "N", diviziune: "81" },
  { cod: "8121", denumire: "Activități generale de curățenie a clădirilor", sectiune: "N", diviziune: "81" },
  { cod: "8129", denumire: "Alte activități de curățenie n.c.a.", sectiune: "N", diviziune: "81" },
  { cod: "8130", denumire: "Activități de întreținere peisagistică", sectiune: "N", diviziune: "81" },
  { cod: "8211", denumire: "Activități combinate de secretariat", sectiune: "N", diviziune: "82" },
  { cod: "8219", denumire: "Activități de fotocopiere, pregătire a documentelor și alte activități specializate de secretariat", sectiune: "N", diviziune: "82" },
  { cod: "8220", denumire: "Activități ale centrelor de intermediere telefonică (call center)", sectiune: "N", diviziune: "82" },
  { cod: "8230", denumire: "Activități de organizare a expozițiilor, târgurilor și congreselor", sectiune: "N", diviziune: "82" },
  { cod: "8291", denumire: "Activități ale agențiilor de colectare și ale birourilor (oficiilor) de credit", sectiune: "N", diviziune: "82" },
  { cod: "8292", denumire: "Activități de ambalare", sectiune: "N", diviziune: "82" },
  { cod: "8299", denumire: "Alte activități de servicii suport pentru întreprinderi n.c.a.", sectiune: "N", diviziune: "82" },
  // O, P, Q - Administrație publică, Învățământ, Sănătate
  { cod: "8411", denumire: "Servicii de administrație publică generală", sectiune: "O", diviziune: "84" },
  { cod: "8510", denumire: "Învățământ preșcolar", sectiune: "P", diviziune: "85" },
  { cod: "8520", denumire: "Învățământ primar", sectiune: "P", diviziune: "85" },
  { cod: "8531", denumire: "Învățământ secundar general", sectiune: "P", diviziune: "85" },
  { cod: "8532", denumire: "Învățământ secundar, tehnic sau profesional", sectiune: "P", diviziune: "85" },
  { cod: "8541", denumire: "Învățământ superior non-universitar", sectiune: "P", diviziune: "85" },
  { cod: "8542", denumire: "Învățământ superior universitar", sectiune: "P", diviziune: "85" },
  { cod: "8551", denumire: "Învățământ în domenii sportive și recreative", sectiune: "P", diviziune: "85" },
  { cod: "8552", denumire: "Învățământ cultural (limbi moderne, muzică, teatru, dans, arte plastice etc.)", sectiune: "P", diviziune: "85" },
  { cod: "8559", denumire: "Alte forme de învățământ n.c.a.", sectiune: "P", diviziune: "85" },
  { cod: "8560", denumire: "Activități de servicii suport pentru învățământ", sectiune: "P", diviziune: "85" },
  { cod: "8610", denumire: "Activități de asistență spitalicească", sectiune: "Q", diviziune: "86" },
  { cod: "8621", denumire: "Activități de asistență medicală generală", sectiune: "Q", diviziune: "86" },
  { cod: "8622", denumire: "Activități de asistență medicală specializată", sectiune: "Q", diviziune: "86" },
  { cod: "8623", denumire: "Activități de asistență stomatologică", sectiune: "Q", diviziune: "86" },
  { cod: "8690", denumire: "Alte activități referitoare la sănătatea umană", sectiune: "Q", diviziune: "86" },
  { cod: "8710", denumire: "Activități ale centrelor de îngrijire medicală", sectiune: "Q", diviziune: "87" },
  { cod: "8720", denumire: "Activități ale centrelor de recuperare psihică și de dezintoxicare, exclusiv spitale", sectiune: "Q", diviziune: "87" },
  // R - Activități de spectacole, culturale și recreative
  { cod: "9001", denumire: "Activități de interpretare artistică (spectacole)", sectiune: "R", diviziune: "90" },
  { cod: "9002", denumire: "Activități suport pentru interpretare artistică (spectacole)", sectiune: "R", diviziune: "90" },
  { cod: "9003", denumire: "Activități de creație artistică", sectiune: "R", diviziune: "90" },
  { cod: "9004", denumire: "Gestionarea sălilor de spectacole", sectiune: "R", diviziune: "90" },
  { cod: "9011", denumire: "Activități ale bibliotecilor și arhivelor", sectiune: "R", diviziune: "91" },
  { cod: "9012", denumire: "Activități ale muzeelor", sectiune: "R", diviziune: "91" },
  { cod: "9013", denumire: "Gestionarea monumentelor, clădirilor istorice și a altor obiective de interes turistic", sectiune: "R", diviziune: "91" },
  { cod: "9021", denumire: "Activități ale parcurilor și grădinilor botanice și zoologice și ale rezervațiilor naturale", sectiune: "R", diviziune: "91" },
  { cod: "9200", denumire: "Activități de jocuri de noroc și pariuri", sectiune: "R", diviziune: "92" },
  { cod: "9311", denumire: "Activități ale bazelor sportive", sectiune: "R", diviziune: "93" },
  { cod: "9312", denumire: "Activități ale cluburilor sportive", sectiune: "R", diviziune: "93" },
  { cod: "9319", denumire: "Alte activități sportive", sectiune: "R", diviziune: "93" },
  { cod: "9321", denumire: "Bâlciuri și parcuri de distracții", sectiune: "R", diviziune: "93" },
  { cod: "9329", denumire: "Alte activități recreative și distractive n.c.a.", sectiune: "R", diviziune: "93" },
  // S - Alte activități de servicii
  { cod: "9411", denumire: "Activități ale organizațiilor economice și patronale", sectiune: "S", diviziune: "94" },
  { cod: "9412", denumire: "Activități ale organizațiilor profesionale", sectiune: "S", diviziune: "94" },
  { cod: "9420", denumire: "Activități ale sindicatelor salariate", sectiune: "S", diviziune: "94" },
  { cod: "9491", denumire: "Activități ale organizațiilor religioase", sectiune: "S", diviziune: "94" },
  { cod: "9499", denumire: "Activități ale altor organizații n.c.a.", sectiune: "S", diviziune: "94" },
  { cod: "9511", denumire: "Repararea calculatoarelor și a echipamentelor periferice", sectiune: "S", diviziune: "95" },
  { cod: "9512", denumire: "Repararea echipamentelor de comunicații", sectiune: "S", diviziune: "95" },
  { cod: "9521", denumire: "Repararea aparatelor electronice de uz casnic", sectiune: "S", diviziune: "95" },
  { cod: "9522", denumire: "Repararea dispozitivelor de uz casnic și a echipamentelor pentru casă și grădină", sectiune: "S", diviziune: "95" },
  { cod: "9523", denumire: "Repararea încălțămintei și a articolelor din piele", sectiune: "S", diviziune: "95" },
  { cod: "9524", denumire: "Repararea mobilei și a furniturilor casnice", sectiune: "S", diviziune: "95" },
  { cod: "9529", denumire: "Repararea altor bunuri de uz personal și gospodăresc", sectiune: "S", diviziune: "95" },
  { cod: "9601", denumire: "Spălarea și curățarea (uscată) articolelor textile și a produselor din blană", sectiune: "S", diviziune: "96" },
  { cod: "9602", denumire: "Coafură și alte activități de înfrumusețare", sectiune: "S", diviziune: "96" },
  { cod: "9603", denumire: "Activități de pompe funebre și similare", sectiune: "S", diviziune: "96" },
  { cod: "9604", denumire: "Activități de întreținere corporală", sectiune: "S", diviziune: "96" },
  { cod: "9609", denumire: "Alte activități de servicii personale n.c.a.", sectiune: "S", diviziune: "96" },
];

async function main() {
  console.log(`Inserare ${coduri.length} coduri CAEN...`);

  await db
    .insert(codurICaenTable)
    .values(coduri)
    .onConflictDoNothing({ target: codurICaenTable.cod });

  const count = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(codurICaenTable)
    .then((r) => r[0]?.count ?? 0);

  console.log(`✓ Coduri CAEN în baza de date: ${count}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Eroare la inserare coduri CAEN:", err);
  process.exit(1);
});
